---
name: CI to Docker Hub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push rstudio-server:latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: ./latest
          file: ./Dockerfile
          push: true
          tags: ${{ github.actor }}/rstudio-server:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}

      - name: Build and push rstudio-server:slim
        id: docker_build_slim
        uses: docker/build-push-action@v2
        with:
          context: ./slim
          file: ./Dockerfile
          push: true
          tags: ${{ github.actor }}/rstudio-server:slim

      - name: Image digest
        run: echo ${{ steps.docker_build_slim.outputs.digest }}
