---
name: CI to Docker Hub

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push images
        env:
          REPOSITORY: ${{ github.actor }}/rstudio-server
        run: |
          for t in 'latest' 'slim'; do
            docker image build -t "${REPOSITORY}:${t}" "${t}" \
              && docker image push "${REPOSITORY}:${t}"
          done
